//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NantCom.MultiStreamer.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.5.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }

        #region FacebookStream
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FacebookStreamURL
        {
            get
            {
                return ((string)(this["FacebookStreamURL"]));
            }
            set
            {
                this["FacebookStreamURL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FacebookStreamKey {
            get {
                return ((string)(this["FacebookStreamKey"]));
            }
            set {
                this["FacebookStreamKey"] = value;
            }
        }
        #endregion

        #region TwitchStream
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchStreamURL
        {
            get {
                return ((string)(this["TwitchStreamURL"]));
            }
            set {
                this["TwitchStreamURL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TwitchStreamKey
        {
            get
            {
                return ((string)(this["TwitchStreamKey"]));
            }
            set
            {
                this["TwitchStreamKey"] = value;
            }
        }
        #endregion

        #region YouTubeStream
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string YouTubeStreamURL
        {
            get
            {
                return ((string)(this["YouTubeStreamURL"]));
            }
            set
            {
                this["YouTubeStreamURL"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string YouTubeStreamKey {
            get {
                return ((string)(this["YouTubeStreamKey"]));
            }
            set {
                this["YouTubeStreamKey"] = value;
            }
        }
        #endregion

        #region Facebook Setting
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("30")]
        public int FacebookFramesPerSecond
        {
            get
            {
                return ((int)(this["FacebookFramesPerSecond"]));
            }
            set
            {
                this["FacebookFramesPerSecond"] = value;
            }
        }

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1280")]
        public int FacebookScale
        {
            get
            {
                return ((int)(this["FacebookScale"]));
            }
            set
            {
                this["FacebookScale"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4000")]
        public int FacebookBitRate {
            get {
                return ((int)(this["FacebookBitRate"]));
            }
            set {
                this["FacebookBitRate"] = value;
            }
        }
        #endregion

        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsLicenseAcknowledged {
            get {
                return ((bool)(this["IsLicenseAcknowledged"]));
            }
            set {
                this["IsLicenseAcknowledged"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool IsStartOBS {
            get {
                return ((bool)(this["IsStartOBS"]));
            }
            set {
                this["IsStartOBS"] = value;
            }
        }
    }
}
